### ISSUE TITLE
IW move message alerts are too fleeting

### ISSUE THREAD

**Issue by kastork** [Longhouse-Games/infochess#31]
It is easy to miss the cool animated messages about IW events.

One suggestion has been to have a status area that permanently (or something) shows the latest IW event message and location on the board (when appropriate)

**Comment by rgould** [comment]
@kastork Came up with an idea like this. What do you think? 

![screen shot 2013-08-22 at 1 28 03 pm](https://f.cloud.github.com/assets/82154/1012095/76297258-0b69-11e3-9657-09375a482ce9.png)
